NYXUS_3D_SHAPE_FEATURES = [
    "3AREA",
    "3AREA_2_VOLUME",
    "3COMPACTNESS1",
    "3COMPACTNESS2",
    "3ELONGATION",
    "3FLATNESS",
    "3LEAST_AXIS_LEN",
    "3MAJOR_AXIS_LEN",
    "3MESH_VOLUME",
    "3MINOR_AXIS_LEN",
    "3SPHERICAL_DISPROPORTION",
    "3SPHERICITY",
    "3VOLUME_CONVEXHULL",
    "3VOXEL_VOLUME"
]

NYXUS_3D_TEXTURE_FEATURES = [
    '3GLCM_ACOR', '3GLCM_ASM', '3GLCM_CLUPROM', '3GLCM_CLUSHADE', '3GLCM_CLUTEND', '3GLCM_CONTRAST', '3GLCM_CORRELATION',
    '3GLCM_DIFAVE', '3GLCM_DIFENTRO', '3GLCM_DIFVAR', '3GLCM_DIS', '3GLCM_ENERGY', '3GLCM_ENTROPY', '3GLCM_HOM1', '3GLCM_HOM2',
    '3GLCM_ID', '3GLCM_IDN', '3GLCM_IDM', '3GLCM_IDMN', '3GLCM_INFOMEAS1', '3GLCM_INFOMEAS2', '3GLCM_IV', '3GLCM_JAVE', '3GLCM_JE',
    '3GLCM_JMAX', '3GLCM_JVAR', '3GLCM_SUMAVERAGE', '3GLCM_SUMENTROPY', '3GLCM_SUMVARIANCE', '3GLCM_VARIANCE', '3GLCM_ASM_AVE',
    '3GLCM_ACOR_AVE', '3GLCM_CLUPROM_AVE', '3GLCM_CLUSHADE_AVE', '3GLCM_CLUTEND_AVE', '3GLCM_CONTRAST_AVE', '3GLCM_CORRELATION_AVE',
    '3GLCM_DIFAVE_AVE', '3GLCM_DIFENTRO_AVE', '3GLCM_DIFVAR_AVE', '3GLCM_DIS_AVE', '3GLCM_ENERGY_AVE', '3GLCM_ENTROPY_AVE',
    '3GLCM_HOM1_AVE', '3GLCM_ID_AVE', '3GLCM_IDN_AVE', '3GLCM_IDM_AVE', '3GLCM_IDMN_AVE', '3GLCM_IV_AVE', '3GLCM_JAVE_AVE',
    '3GLCM_JE_AVE', '3GLCM_INFOMEAS1_AVE', '3GLCM_INFOMEAS2_AVE', '3GLCM_VARIANCE_AVE', '3GLCM_JMAX_AVE', '3GLCM_JVAR_AVE',
    '3GLCM_SUMAVERAGE_AVE', '3GLCM_SUMENTROPY_AVE', '3GLCM_SUMVARIANCE_AVE', '3GLDM_SDE', '3GLDM_LDE', '3GLDM_GLN', '3GLDM_DN',
    '3GLDM_DNN', '3GLDM_GLV', '3GLDM_DV', '3GLDM_DE', '3GLDM_LGLE', '3GLDM_HGLE', '3GLDM_SDLGLE', '3GLDM_SDHGLE', '3GLDM_LDLGLE',
    '3GLDM_LDHGLE', '3GLDZM_SDE', '3GLDZM_LDE', '3GLDZM_LGLZE', '3GLDZM_HGLZE', '3GLDZM_SDLGLE', '3GLDZM_SDHGLE', '3GLDZM_LDLGLE',
    '3GLDZM_LDHGLE', '3GLDZM_GLNU', '3GLDZM_GLNUN', '3GLDZM_ZDNU', '3GLDZM_ZDNUN', '3GLDZM_ZP', '3GLDZM_GLM', '3GLDZM_GLV', '3GLDZM_ZDM',
    '3GLDZM_ZDV', '3GLDZM_ZDE', '3NGLDM_LDE', '3NGLDM_HDE', '3NGLDM_LGLCE', '3NGLDM_HGLCE', '3NGLDM_LDLGLE', '3NGLDM_LDHGLE',
    '3NGLDM_HDLGLE', '3NGLDM_HDHGLE', '3NGLDM_GLNU', '3NGLDM_GLNUN', '3NGLDM_DCNU', '3NGLDM_DCNUN', '3NGLDM_DCP', '3NGLDM_GLM',
    '3NGLDM_GLV', '3NGLDM_DCM', '3NGLDM_DCV', '3NGLDM_DCENT', '3NGLDM_DCENE', '3NGTDM_COARSENESS', '3NGTDM_CONTRAST', '3NGTDM_BUSYNESS',
    '3NGTDM_COMPLEXITY', '3NGTDM_STRENGTH', '3GLSZM_SAE', '3GLSZM_LAE', '3GLSZM_GLN', '3GLSZM_GLNN', '3GLSZM_SZN', '3GLSZM_SZNN',
    '3GLSZM_ZP', '3GLSZM_GLV', '3GLSZM_ZV', '3GLSZM_ZE', '3GLSZM_LGLZE', '3GLSZM_HGLZE', '3GLSZM_SALGLE', '3GLSZM_SAHGLE',
    '3GLSZM_LALGLE', '3GLSZM_LAHGLE', '3GLRLM_SRE', '3GLRLM_LRE', '3GLRLM_GLN', '3GLRLM_GLNN', '3GLRLM_RLN', '3GLRLM_RLNN',
    '3GLRLM_RP', '3GLRLM_GLV', '3GLRLM_RV', '3GLRLM_RE', '3GLRLM_LGLRE', '3GLRLM_HGLRE', '3GLRLM_SRLGLE', '3GLRLM_SRHGLE',
    '3GLRLM_LRLGLE', '3GLRLM_LRHGLE', '3GLRLM_SRE_AVE', '3GLRLM_LRE_AVE', '3GLRLM_GLN_AVE', '3GLRLM_GLNN_AVE', '3GLRLM_RLN_AVE',
    '3GLRLM_RLNN_AVE', '3GLRLM_RP_AVE', '3GLRLM_GLV_AVE', '3GLRLM_RV_AVE', '3GLRLM_RE_AVE', '3GLRLM_LGLRE_AVE', '3GLRLM_HGLRE_AVE',
    '3GLRLM_SRLGLE_AVE', '3GLRLM_SRHGLE_AVE', '3GLRLM_LRLGLE_AVE', '3GLRLM_LRHGLE_AVE'
]


NYXUS_3D_FIRSTORDER_FEATURES = [
    "3COV",
    "3COVERED_IMAGE_INTENSITY_RANGE",
    "3ENERGY",
    "3ENTROPY",
    "3EXCESS_KURTOSIS",
    "3HYPERFLATNESS",
    "3HYPERSKEWNESS",
    "3INTEGRATED_INTENSITY",
    "3INTERQUARTILE_RANGE",
    "3KURTOSIS",
    "3MAX",
    "3MEAN",
    "3MEAN_ABSOLUTE_DEVIATION",
    "3MEDIAN",
    "3MEDIAN_ABSOLUTE_DEVIATION",
    "3MIN",
    "3MODE",
    "3P01",
    "3P10",
    "3P25",
    "3P75",
    "3P90",
    "3P99",
    "3QCOD",
    "3RANGE",
    "3ROBUST_MEAN",
    "3ROBUST_MEAN_ABSOLUTE_DEVIATION",
    "3ROOT_MEAN_SQUARED",
    "3SKEWNESS",
    "3STANDARD_DEVIATION",
    "3STANDARD_DEVIATION_BIASED",
    "3STANDARD_ERROR",
    "3VARIANCE",
    "3VARIANCE_BIASED",
    "3UNIFORMITY",
    "3UNIFORMITY_PIU"
]

NYXUS_3D_ALL_FEATURES = NYXUS_3D_SHAPE_FEATURES + NYXUS_3D_TEXTURE_FEATURES + NYXUS_3D_FIRSTORDER_FEATURES


NYXUS_2D_FIRSTORDER_FEATURES = [
    "COV", "COVERED_IMAGE_INTENSITY_RANGE", "ENERGY", "ENTROPY", "EXCESS_KURTOSIS",
    "HYPERFLATNESS", "HYPERSKEWNESS", "INTEGRATED_INTENSITY", "INTERQUARTILE_RANGE",
    "KURTOSIS", "MAX", "MEAN", "MEAN_ABSOLUTE_DEVIATION", "MEDIAN",
    "MEDIAN_ABSOLUTE_DEVIATION", "MIN", "MODE", "P01", "P10", "P25", "P75",
    "P90", "P99", "QCOD", "RANGE", "ROBUST_MEAN", "ROBUST_MEAN_ABSOLUTE_DEVIATION",
    "ROOT_MEAN_SQUARED", "SKEWNESS", "STANDARD_DEVIATION", "STANDARD_DEVIATION_BIASED",
    "STANDARD_ERROR", "VARIANCE", "VARIANCE_BIASED", "UNIFORMITY", "UNIFORMITY_PIU"
]

# 2D Shape/Morphological Features
NYXUS_2D_SHAPE_FEATURES = [
    "AREA_PIXELS_COUNT", "AREA_UM2", "CENTROID_X", "CENTROID_Y", "WEIGHTED_CENTROID_Y",
    "WEIGHTED_CENTROID_X", "MASS_DISPLACEMENT", "COMPACTNESS", "BBOX_YMIN", "BBOX_XMIN",
    "BBOX_HEIGHT", "BBOX_WIDTH", "DIAMETER_EQUAL_AREA", "EXTENT", "ASPECT_RATIO",
    "MAJOR_AXIS_LENGTH", "MINOR_AXIS_LENGTH", "ELONGATION", "ECCENTRICITY", "ORIENTATION",
    "ROUNDNESS", "PERIMETER", "DIAMETER_EQUAL_PERIMETER", "CIRCULARITY", "CONVEX_HULL_AREA",
    "SOLIDITY", "EROSIONS_2_VANISH", "EROSIONS_2_VANISH_COMPLEMENT", "FRACT_DIM_BOXCOUNT",
    "FRACT_DIM_PERIMETER", "MIN_FERET_ANGLE", "MAX_FERET_ANGLE", "STAT_FERET_DIAM_MIN",
    "STAT_FERET_DIAM_MAX", "STAT_FERET_DIAM_MEAN", "STAT_FERET_DIAM_MEDIAN",
    "STAT_FERET_DIAM_STDDEV", "STAT_FERET_DIAM_MODE", "STAT_MARTIN_DIAM_MIN",
    "STAT_MARTIN_DIAM_MAX", "STAT_MARTIN_DIAM_MEAN", "STAT_MARTIN_DIAM_MEDIAN",
    "STAT_MARTIN_DIAM_STDDEV", "STAT_MARTIN_DIAM_MODE", "STAT_NASSENSTEIN_DIAM_MIN",
    "STAT_NASSENSTEIN_DIAM_MAX", "STAT_NASSENSTEIN_DIAM_MEAN", "STAT_NASSENSTEIN_DIAM_MEDIAN",
    "STAT_NASSENSTEIN_DIAM_STDDEV", "STAT_NASSENSTEIN_DIAM_MODE", "MAXCHORDS_MAX",
    "MAXCHORDS_MAX_ANG", "MAXCHORDS_MIN", "MAXCHORDS_MIN_ANG", "MAXCHORDS_MEDIAN",
    "MAXCHORDS_MEAN", "MAXCHORDS_MODE", "MAXCHORDS_STDDEV", "ALLCHORDS_MAX",
    "ALLCHORDS_MAX_ANG", "ALLCHORDS_MIN", "ALLCHORDS_MIN_ANG", "ALLCHORDS_MEDIAN",
    "ALLCHORDS_MEAN", "ALLCHORDS_MODE", "ALLCHORDS_STDDEV", "EULER_NUMBER",
    "EXTREMA_P1_X", "EXTREMA_P1_Y", "EXTREMA_P2_X", "EXTREMA_P2_Y", "EXTREMA_P3_X",
    "EXTREMA_P3_Y", "EXTREMA_P4_X", "EXTREMA_P4_Y", "EXTREMA_P5_X", "EXTREMA_P5_Y",
    "EXTREMA_P6_X", "EXTREMA_P6_Y", "EXTREMA_P7_X", "EXTREMA_P7_Y", "EXTREMA_P8_X",
    "EXTREMA_P8_Y", "POLYGONALITY_AVE", "HEXAGONALITY_AVE", "HEXAGONALITY_STDDEV",
    "DIAMETER_MIN_ENCLOSING_CIRCLE", "DIAMETER_CIRCUMSCRIBING_CIRCLE",
    "DIAMETER_INSCRIBING_CIRCLE", "GEODETIC_LENGTH", "THICKNESS", "ROI_RADIUS_MEAN",
    "ROI_RADIUS_MAX", "ROI_RADIUS_MEDIAN", "NUM_NEIGHBORS", "PERCENT_TOUCHING",
    "CLOSEST_NEIGHBOR1_DIST", "CLOSEST_NEIGHBOR1_ANG", "CLOSEST_NEIGHBOR2_DIST",
    "CLOSEST_NEIGHBOR2_ANG", "ANG_BW_NEIGHBORS_MEAN", "ANG_BW_NEIGHBORS_STDDEV",
    "ANG_BW_NEIGHBORS_MODE"
]

# 2D Edge Features
NYXUS_2D_EDGE_FEATURES = [
    "EDGE_MEAN_INTENSITY", "EDGE_STDDEV_INTENSITY", "EDGE_MAX_INTENSITY",
    "EDGE_MIN_INTENSITY", "EDGE_INTEGRATED_INTENSITY"
]

# 2D Texture Features - GLCM (directional: 0, 45, 90, 135 degrees)
NYXUS_2D_GLCM_DIRECTIONAL = [
    "GLCM_ASM_0", "GLCM_ASM_45", "GLCM_ASM_90", "GLCM_ASM_135",
    "GLCM_ACOR_0", "GLCM_ACOR_45", "GLCM_ACOR_90", "GLCM_ACOR_135",
    "GLCM_CLUPROM_0", "GLCM_CLUPROM_45", "GLCM_CLUPROM_90", "GLCM_CLUPROM_135",
    "GLCM_CLUSHADE_0", "GLCM_CLUSHADE_45", "GLCM_CLUSHADE_90", "GLCM_CLUSHADE_135",
    "GLCM_CLUTEND_0", "GLCM_CLUTEND_45", "GLCM_CLUTEND_90", "GLCM_CLUTEND_135",
    "GLCM_CONTRAST_0", "GLCM_CONTRAST_45", "GLCM_CONTRAST_90", "GLCM_CONTRAST_135",
    "GLCM_CORRELATION_0", "GLCM_CORRELATION_45", "GLCM_CORRELATION_90", "GLCM_CORRELATION_135",
    "GLCM_DIFAVE_0", "GLCM_DIFAVE_45", "GLCM_DIFAVE_90", "GLCM_DIFAVE_135",
    "GLCM_DIFENTRO_0", "GLCM_DIFENTRO_45", "GLCM_DIFENTRO_90", "GLCM_DIFENTRO_135",
    "GLCM_DIFVAR_0", "GLCM_DIFVAR_45", "GLCM_DIFVAR_90", "GLCM_DIFVAR_135",
    "GLCM_DIS_0", "GLCM_DIS_45", "GLCM_DIS_90", "GLCM_DIS_135",
    "GLCM_ENERGY_0", "GLCM_ENERGY_45", "GLCM_ENERGY_90", "GLCM_ENERGY_135",
    "GLCM_ENTROPY_0", "GLCM_ENTROPY_45", "GLCM_ENTROPY_90", "GLCM_ENTROPY_135",
    "GLCM_HOM1_0", "GLCM_HOM1_45", "GLCM_HOM1_90", "GLCM_HOM1_135",
    "GLCM_HOM2_0", "GLCM_HOM2_45", "GLCM_HOM2_90", "GLCM_HOM2_135",
    "GLCM_ID_0", "GLCM_ID_45", "GLCM_ID_90", "GLCM_ID_135",
    "GLCM_IDN_0", "GLCM_IDN_45", "GLCM_IDN_90", "GLCM_IDN_135",
    "GLCM_IDM_0", "GLCM_IDM_45", "GLCM_IDM_90", "GLCM_IDM_135",
    "GLCM_IDMN_0", "GLCM_IDMN_45", "GLCM_IDMN_90", "GLCM_IDMN_135",
    "GLCM_INFOMEAS1_0", "GLCM_INFOMEAS1_45", "GLCM_INFOMEAS1_90", "GLCM_INFOMEAS1_135",
    "GLCM_INFOMEAS2_0", "GLCM_INFOMEAS2_45", "GLCM_INFOMEAS2_90", "GLCM_INFOMEAS2_135",
    "GLCM_IV_0", "GLCM_IV_45", "GLCM_IV_90", "GLCM_IV_135",
    "GLCM_JAVE_0", "GLCM_JAVE_45", "GLCM_JAVE_90", "GLCM_JAVE_135",
    "GLCM_JE_0", "GLCM_JE_45", "GLCM_JE_90", "GLCM_JE_135",
    "GLCM_JMAX_0", "GLCM_JMAX_45", "GLCM_JMAX_90", "GLCM_JMAX_135",
    "GLCM_JVAR_0", "GLCM_JVAR_45", "GLCM_JVAR_90", "GLCM_JVAR_135",
    "GLCM_SUMAVERAGE_0", "GLCM_SUMAVERAGE_45", "GLCM_SUMAVERAGE_90", "GLCM_SUMAVERAGE_135",
    "GLCM_SUMENTROPY_0", "GLCM_SUMENTROPY_45", "GLCM_SUMENTROPY_90", "GLCM_SUMENTROPY_135",
    "GLCM_SUMVARIANCE_0", "GLCM_SUMVARIANCE_45", "GLCM_SUMVARIANCE_90", "GLCM_SUMVARIANCE_135",
    "GLCM_VARIANCE_0", "GLCM_VARIANCE_45", "GLCM_VARIANCE_90", "GLCM_VARIANCE_135"
]

# 2D Texture Features - GLCM Averaged
NYXUS_2D_GLCM_AVERAGED = [
    "GLCM_ASM_AVE", "GLCM_ACOR_AVE", "GLCM_CLUPROM_AVE", "GLCM_CLUSHADE_AVE",
    "GLCM_CLUTEND_AVE", "GLCM_CONTRAST_AVE", "GLCM_CORRELATION_AVE", "GLCM_DIFAVE_AVE",
    "GLCM_DIFENTRO_AVE", "GLCM_DIFVAR_AVE", "GLCM_DIS_AVE", "GLCM_ENERGY_AVE",
    "GLCM_ENTROPY_AVE", "GLCM_HOM1_AVE", "GLCM_ID_AVE", "GLCM_IDN_AVE",
    "GLCM_IDM_AVE", "GLCM_IDMN_AVE", "GLCM_IV_AVE", "GLCM_JAVE_AVE",
    "GLCM_JE_AVE", "GLCM_INFOMEAS1_AVE", "GLCM_INFOMEAS2_AVE", "GLCM_VARIANCE_AVE",
    "GLCM_JMAX_AVE", "GLCM_JVAR_AVE", "GLCM_SUMAVERAGE_AVE", "GLCM_SUMENTROPY_AVE",
    "GLCM_SUMVARIANCE_AVE"
]

# 2D Texture Features - GLRLM (directional)
NYXUS_2D_GLRLM_DIRECTIONAL = [
    "GLRLM_SRE_0", "GLRLM_SRE_45", "GLRLM_SRE_90", "GLRLM_SRE_135",
    "GLRLM_LRE_0", "GLRLM_LRE_45", "GLRLM_LRE_90", "GLRLM_LRE_135",
    "GLRLM_GLN_0", "GLRLM_GLN_45", "GLRLM_GLN_90", "GLRLM_GLN_135",
    "GLRLM_GLNN_0", "GLRLM_GLNN_45", "GLRLM_GLNN_90", "GLRLM_GLNN_135",
    "GLRLM_RLN_0", "GLRLM_RLN_45", "GLRLM_RLN_90", "GLRLM_RLN_135",
    "GLRLM_RLNN_0", "GLRLM_RLNN_45", "GLRLM_RLNN_90", "GLRLM_RLNN_135",
    "GLRLM_RP_0", "GLRLM_RP_45", "GLRLM_RP_90", "GLRLM_RP_135",
    "GLRLM_GLV_0", "GLRLM_GLV_45", "GLRLM_GLV_90", "GLRLM_GLV_135",
    "GLRLM_RV_0", "GLRLM_RV_45", "GLRLM_RV_90", "GLRLM_RV_135",
    "GLRLM_RE_0", "GLRLM_RE_45", "GLRLM_RE_90", "GLRLM_RE_135",
    "GLRLM_LGLRE_0", "GLRLM_LGLRE_45", "GLRLM_LGLRE_90", "GLRLM_LGLRE_135",
    "GLRLM_HGLRE_0", "GLRLM_HGLRE_45", "GLRLM_HGLRE_90", "GLRLM_HGLRE_135",
    "GLRLM_SRLGLE_0", "GLRLM_SRLGLE_45", "GLRLM_SRLGLE_90", "GLRLM_SRLGLE_135",
    "GLRLM_SRHGLE_0", "GLRLM_SRHGLE_45", "GLRLM_SRHGLE_90", "GLRLM_SRHGLE_135",
    "GLRLM_LRLGLE_0", "GLRLM_LRLGLE_45", "GLRLM_LRLGLE_90", "GLRLM_LRLGLE_135",
    "GLRLM_LRHGLE_0", "GLRLM_LRHGLE_45", "GLRLM_LRHGLE_90", "GLRLM_LRHGLE_135"
]

# 2D Texture Features - GLRLM Averaged
NYXUS_2D_GLRLM_AVERAGED = [
    "GLRLM_SRE_AVE", "GLRLM_LRE_AVE", "GLRLM_GLN_AVE", "GLRLM_GLNN_AVE",
    "GLRLM_RLN_AVE", "GLRLM_RLNN_AVE", "GLRLM_RP_AVE", "GLRLM_GLV_AVE",
    "GLRLM_RV_AVE", "GLRLM_RE_AVE", "GLRLM_LGLRE_AVE", "GLRLM_HGLRE_AVE",
    "GLRLM_SRLGLE_AVE", "GLRLM_SRHGLE_AVE", "GLRLM_LRLGLE_AVE", "GLRLM_LRHGLE_AVE"
]

# 2D Texture Features - Other texture matrices
NYXUS_2D_TEXTURE_OTHER = [
    "GLDZM_SDE", "GLDZM_LDE", "GLDZM_LGLZE", "GLDZM_HGLZE", "GLDZM_SDLGLE",
    "GLDZM_SDHGLE", "GLDZM_LDLGLE", "GLDZM_LDHGLE", "GLDZM_GLNU", "GLDZM_GLNUN",
    "GLDZM_ZDNU", "GLDZM_ZDNUN", "GLDZM_ZP", "GLDZM_GLM", "GLDZM_GLV", "GLDZM_ZDM",
    "GLDZM_ZDV", "GLDZM_ZDE", "GLSZM_SAE", "GLSZM_LAE", "GLSZM_GLN", "GLSZM_GLNN",
    "GLSZM_SZN", "GLSZM_SZNN", "GLSZM_ZP", "GLSZM_GLV", "GLSZM_ZV", "GLSZM_ZE",
    "GLSZM_LGLZE", "GLSZM_HGLZE", "GLSZM_SALGLE", "GLSZM_SAHGLE", "GLSZM_LALGLE",
    "GLSZM_LAHGLE", "GLDM_SDE", "GLDM_LDE", "GLDM_GLN", "GLDM_DN", "GLDM_DNN",
    "GLDM_GLV", "GLDM_DV", "GLDM_DE", "GLDM_LGLE", "GLDM_HGLE", "GLDM_SDLGLE",
    "GLDM_SDHGLE", "GLDM_LDLGLE", "GLDM_LDHGLE", "NGLDM_LDE", "NGLDM_HDE",
    "NGLDM_LGLCE", "NGLDM_HGLCE", "NGLDM_LDLGLE", "NGLDM_LDHGLE", "NGLDM_HDLGLE",
    "NGLDM_HDHGLE", "NGLDM_GLNU", "NGLDM_GLNUN", "NGLDM_DCNU", "NGLDM_DCNUN",
    "NGLDM_DCP", "NGLDM_GLM", "NGLDM_GLV", "NGLDM_DCM", "NGLDM_DCV", "NGLDM_DCENT",
    "NGLDM_DCENE", "NGTDM_COARSENESS", "NGTDM_CONTRAST", "NGTDM_BUSYNESS",
    "NGTDM_COMPLEXITY", "NGTDM_STRENGTH"
]

# 2D Specialized Features
NYXUS_2D_SPECIALIZED_FEATURES = [
    "FRAC_AT_D_0", "FRAC_AT_D_1", "FRAC_AT_D_2", "FRAC_AT_D_3", "FRAC_AT_D_4",
    "FRAC_AT_D_5", "FRAC_AT_D_6", "FRAC_AT_D_7", "GABOR_0", "GABOR_1", "GABOR_2",
    "GABOR_3", "MEAN_FRAC_0", "MEAN_FRAC_1", "MEAN_FRAC_2", "MEAN_FRAC_3",
    "MEAN_FRAC_4", "MEAN_FRAC_5", "MEAN_FRAC_6", "MEAN_FRAC_7", "RADIAL_CV_0",
    "RADIAL_CV_1", "RADIAL_CV_2", "RADIAL_CV_3", "RADIAL_CV_4", "RADIAL_CV_5",
    "RADIAL_CV_6", "RADIAL_CV_7", "ZERNIKE2D_Z0", "ZERNIKE2D_Z1", "ZERNIKE2D_Z2",
    "ZERNIKE2D_Z3", "ZERNIKE2D_Z4", "ZERNIKE2D_Z5", "ZERNIKE2D_Z6", "ZERNIKE2D_Z7",
    "ZERNIKE2D_Z8", "ZERNIKE2D_Z9", "ZERNIKE2D_Z10", "ZERNIKE2D_Z11", "ZERNIKE2D_Z12",
    "ZERNIKE2D_Z13", "ZERNIKE2D_Z14", "ZERNIKE2D_Z15", "ZERNIKE2D_Z16", "ZERNIKE2D_Z17",
    "ZERNIKE2D_Z18", "ZERNIKE2D_Z19", "ZERNIKE2D_Z20", "ZERNIKE2D_Z21", "ZERNIKE2D_Z22",
    "ZERNIKE2D_Z23", "ZERNIKE2D_Z24", "ZERNIKE2D_Z25", "ZERNIKE2D_Z26", "ZERNIKE2D_Z27",
    "ZERNIKE2D_Z28", "ZERNIKE2D_Z29"
]

# 2D Moment Features
NYXUS_2D_MOMENT_FEATURES = [
    "SPAT_MOMENT_00", "SPAT_MOMENT_01", "SPAT_MOMENT_02", "SPAT_MOMENT_03",
    "SPAT_MOMENT_10", "SPAT_MOMENT_11", "SPAT_MOMENT_12", "SPAT_MOMENT_13",
    "SPAT_MOMENT_20", "SPAT_MOMENT_21", "SPAT_MOMENT_22", "SPAT_MOMENT_23",
    "SPAT_MOMENT_30", "CENTRAL_MOMENT_00", "CENTRAL_MOMENT_01", "CENTRAL_MOMENT_02",
    "CENTRAL_MOMENT_03", "CENTRAL_MOMENT_10", "CENTRAL_MOMENT_11", "CENTRAL_MOMENT_12",
    "CENTRAL_MOMENT_13", "CENTRAL_MOMENT_20", "CENTRAL_MOMENT_21", "CENTRAL_MOMENT_22",
    "CENTRAL_MOMENT_23", "CENTRAL_MOMENT_30", "CENTRAL_MOMENT_31", "CENTRAL_MOMENT_32",
    "CENTRAL_MOMENT_33", "NORM_SPAT_MOMENT_00", "NORM_SPAT_MOMENT_01", "NORM_SPAT_MOMENT_02",
    "NORM_SPAT_MOMENT_03", "NORM_SPAT_MOMENT_10", "NORM_SPAT_MOMENT_11", "NORM_SPAT_MOMENT_12",
    "NORM_SPAT_MOMENT_13", "NORM_SPAT_MOMENT_20", "NORM_SPAT_MOMENT_21", "NORM_SPAT_MOMENT_22",
    "NORM_SPAT_MOMENT_23", "NORM_SPAT_MOMENT_30", "NORM_SPAT_MOMENT_31", "NORM_SPAT_MOMENT_32",
    "NORM_SPAT_MOMENT_33", "NORM_CENTRAL_MOMENT_02", "NORM_CENTRAL_MOMENT_03",
    "NORM_CENTRAL_MOMENT_11", "NORM_CENTRAL_MOMENT_12", "NORM_CENTRAL_MOMENT_20",
    "NORM_CENTRAL_MOMENT_21", "NORM_CENTRAL_MOMENT_30", "HU_M1", "HU_M2", "HU_M3",
    "HU_M4", "HU_M5", "HU_M6", "HU_M7", "WEIGHTED_SPAT_MOMENT_00", "WEIGHTED_SPAT_MOMENT_01",
    "WEIGHTED_SPAT_MOMENT_02", "WEIGHTED_SPAT_MOMENT_03", "WEIGHTED_SPAT_MOMENT_10",
    "WEIGHTED_SPAT_MOMENT_11", "WEIGHTED_SPAT_MOMENT_12", "WEIGHTED_SPAT_MOMENT_20",
    "WEIGHTED_SPAT_MOMENT_21", "WEIGHTED_SPAT_MOMENT_30", "WEIGHTED_CENTRAL_MOMENT_02",
    "WEIGHTED_CENTRAL_MOMENT_03", "WEIGHTED_CENTRAL_MOMENT_11", "WEIGHTED_CENTRAL_MOMENT_12",
    "WEIGHTED_CENTRAL_MOMENT_20", "WEIGHTED_CENTRAL_MOMENT_21", "WEIGHTED_CENTRAL_MOMENT_30",
    "WT_NORM_CTR_MOM_02", "WT_NORM_CTR_MOM_03", "WT_NORM_CTR_MOM_11", "WT_NORM_CTR_MOM_12",
    "WT_NORM_CTR_MOM_20", "WT_NORM_CTR_MOM_21", "WT_NORM_CTR_MOM_30", "WEIGHTED_HU_M1",
    "WEIGHTED_HU_M2", "WEIGHTED_HU_M3", "WEIGHTED_HU_M4", "WEIGHTED_HU_M5", "WEIGHTED_HU_M6",
    "WEIGHTED_HU_M7", "IMOM_RM_00", "IMOM_RM_01", "IMOM_RM_02", "IMOM_RM_03", "IMOM_RM_10",
    "IMOM_RM_11", "IMOM_RM_12", "IMOM_RM_13", "IMOM_RM_20", "IMOM_RM_21", "IMOM_RM_22",
    "IMOM_RM_23", "IMOM_RM_30", "IMOM_CM_00", "IMOM_CM_01", "IMOM_CM_02", "IMOM_CM_03",
    "IMOM_CM_10", "IMOM_CM_11", "IMOM_CM_12", "IMOM_CM_13", "IMOM_CM_20", "IMOM_CM_21",
    "IMOM_CM_22", "IMOM_CM_23", "IMOM_CM_30", "IMOM_CM_31", "IMOM_CM_32", "IMOM_CM_33",
    "IMOM_NRM_00", "IMOM_NRM_01", "IMOM_NRM_02", "IMOM_NRM_03", "IMOM_NRM_10", "IMOM_NRM_11",
    "IMOM_NRM_12", "IMOM_NRM_13", "IMOM_NRM_20", "IMOM_NRM_21", "IMOM_NRM_22", "IMOM_NRM_23",
    "IMOM_NRM_30", "IMOM_NRM_31", "IMOM_NRM_32", "IMOM_NRM_33", "IMOM_NCM_02", "IMOM_NCM_03",
    "IMOM_NCM_11", "IMOM_NCM_12", "IMOM_NCM_20", "IMOM_NCM_21", "IMOM_NCM_30", "IMOM_HU1",
    "IMOM_HU2", "IMOM_HU3", "IMOM_HU4", "IMOM_HU5", "IMOM_HU6", "IMOM_HU7", "IMOM_WRM_00",
    "IMOM_WRM_01", "IMOM_WRM_02", "IMOM_WRM_03", "IMOM_WRM_10", "IMOM_WRM_11", "IMOM_WRM_12",
    "IMOM_WRM_20", "IMOM_WRM_21", "IMOM_WRM_30", "IMOM_WCM_02", "IMOM_WCM_03", "IMOM_WCM_11",
    "IMOM_WCM_12", "IMOM_WCM_20", "IMOM_WCM_21", "IMOM_WCM_30", "IMOM_WNCM_02", "IMOM_WNCM_03",
    "IMOM_WNCM_11", "IMOM_WNCM_12", "IMOM_WNCM_20", "IMOM_WNCM_21", "IMOM_WNCM_30",
    "IMOM_WHU1", "IMOM_WHU2", "IMOM_WHU3", "IMOM_WHU4", "IMOM_WHU5", "IMOM_WHU6", "IMOM_WHU7"
]

# Combine all 2D texture features
NYXUS_2D_TEXTURE_FEATURES = (
    NYXUS_2D_GLCM_DIRECTIONAL + NYXUS_2D_GLCM_AVERAGED +
    NYXUS_2D_GLRLM_DIRECTIONAL + NYXUS_2D_GLRLM_AVERAGED +
    NYXUS_2D_TEXTURE_OTHER
)

# All 2D Wholeslide Features (exact list, excluding metadata: intensity_image, mask_image, ROI_label)
NYXUS_2D_WHOLESLIDE_FEATURES = [
    # Firstorder (37 features)
    "COV", "COVERED_IMAGE_INTENSITY_RANGE", "ENERGY", "ENTROPY", "EXCESS_KURTOSIS",
    "HYPERFLATNESS", "HYPERSKEWNESS", "INTEGRATED_INTENSITY", "INTERQUARTILE_RANGE",
    "KURTOSIS", "MAX", "MEAN", "MEAN_ABSOLUTE_DEVIATION", "MEDIAN",
    "MEDIAN_ABSOLUTE_DEVIATION", "MIN", "MODE", "P01", "P10", "P25", "P75",
    "P90", "P99", "QCOD", "RANGE", "ROBUST_MEAN", "ROBUST_MEAN_ABSOLUTE_DEVIATION",
    "ROOT_MEAN_SQUARED", "SKEWNESS", "STANDARD_DEVIATION", "STANDARD_DEVIATION_BIASED",
    "STANDARD_ERROR", "VARIANCE", "VARIANCE_BIASED", "UNIFORMITY", "UNIFORMITY_PIU",
    # Shape (2 features)
    "PERIMETER", "DIAMETER_EQUAL_PERIMETER",
    # Edge (5 features)
    "EDGE_MEAN_INTENSITY", "EDGE_STDDEV_INTENSITY", "EDGE_MAX_INTENSITY",
    "EDGE_MIN_INTENSITY", "EDGE_INTEGRATED_INTENSITY",
    # GLCM Directional (144 features)
    "GLCM_ASM_0", "GLCM_ASM_45", "GLCM_ASM_90", "GLCM_ASM_135",
    "GLCM_ACOR_0", "GLCM_ACOR_45", "GLCM_ACOR_90", "GLCM_ACOR_135",
    "GLCM_CLUPROM_0", "GLCM_CLUPROM_45", "GLCM_CLUPROM_90", "GLCM_CLUPROM_135",
    "GLCM_CLUSHADE_0", "GLCM_CLUSHADE_45", "GLCM_CLUSHADE_90", "GLCM_CLUSHADE_135",
    "GLCM_CLUTEND_0", "GLCM_CLUTEND_45", "GLCM_CLUTEND_90", "GLCM_CLUTEND_135",
    "GLCM_CONTRAST_0", "GLCM_CONTRAST_45", "GLCM_CONTRAST_90", "GLCM_CONTRAST_135",
    "GLCM_CORRELATION_0", "GLCM_CORRELATION_45", "GLCM_CORRELATION_90", "GLCM_CORRELATION_135",
    "GLCM_DIFAVE_0", "GLCM_DIFAVE_45", "GLCM_DIFAVE_90", "GLCM_DIFAVE_135",
    "GLCM_DIFENTRO_0", "GLCM_DIFENTRO_45", "GLCM_DIFENTRO_90", "GLCM_DIFENTRO_135",
    "GLCM_DIFVAR_0", "GLCM_DIFVAR_45", "GLCM_DIFVAR_90", "GLCM_DIFVAR_135",
    "GLCM_DIS_0", "GLCM_DIS_45", "GLCM_DIS_90", "GLCM_DIS_135",
    "GLCM_ENERGY_0", "GLCM_ENERGY_45", "GLCM_ENERGY_90", "GLCM_ENERGY_135",
    "GLCM_ENTROPY_0", "GLCM_ENTROPY_45", "GLCM_ENTROPY_90", "GLCM_ENTROPY_135",
    "GLCM_HOM1_0", "GLCM_HOM1_45", "GLCM_HOM1_90", "GLCM_HOM1_135",
    "GLCM_HOM2_0", "GLCM_HOM2_45", "GLCM_HOM2_90", "GLCM_HOM2_135",
    "GLCM_ID_0", "GLCM_ID_45", "GLCM_ID_90", "GLCM_ID_135",
    "GLCM_IDN_0", "GLCM_IDN_45", "GLCM_IDN_90", "GLCM_IDN_135",
    "GLCM_IDM_0", "GLCM_IDM_45", "GLCM_IDM_90", "GLCM_IDM_135",
    "GLCM_IDMN_0", "GLCM_IDMN_45", "GLCM_IDMN_90", "GLCM_IDMN_135",
    "GLCM_INFOMEAS1_0", "GLCM_INFOMEAS1_45", "GLCM_INFOMEAS1_90", "GLCM_INFOMEAS1_135",
    "GLCM_INFOMEAS2_0", "GLCM_INFOMEAS2_45", "GLCM_INFOMEAS2_90", "GLCM_INFOMEAS2_135",
    "GLCM_IV_0", "GLCM_IV_45", "GLCM_IV_90", "GLCM_IV_135",
    "GLCM_JAVE_0", "GLCM_JAVE_45", "GLCM_JAVE_90", "GLCM_JAVE_135",
    "GLCM_JE_0", "GLCM_JE_45", "GLCM_JE_90", "GLCM_JE_135",
    "GLCM_JMAX_0", "GLCM_JMAX_45", "GLCM_JMAX_90", "GLCM_JMAX_135",
    "GLCM_JVAR_0", "GLCM_JVAR_45", "GLCM_JVAR_90", "GLCM_JVAR_135",
    "GLCM_SUMAVERAGE_0", "GLCM_SUMAVERAGE_45", "GLCM_SUMAVERAGE_90", "GLCM_SUMAVERAGE_135",
    "GLCM_SUMENTROPY_0", "GLCM_SUMENTROPY_45", "GLCM_SUMENTROPY_90", "GLCM_SUMENTROPY_135",
    "GLCM_SUMVARIANCE_0", "GLCM_SUMVARIANCE_45", "GLCM_SUMVARIANCE_90", "GLCM_SUMVARIANCE_135",
    "GLCM_VARIANCE_0", "GLCM_VARIANCE_45", "GLCM_VARIANCE_90", "GLCM_VARIANCE_135",
    # GLCM Averaged (28 features)
    "GLCM_ASM_AVE", "GLCM_ACOR_AVE", "GLCM_CLUPROM_AVE", "GLCM_CLUSHADE_AVE",
    "GLCM_CLUTEND_AVE", "GLCM_CONTRAST_AVE", "GLCM_CORRELATION_AVE", "GLCM_DIFAVE_AVE",
    "GLCM_DIFENTRO_AVE", "GLCM_DIFVAR_AVE", "GLCM_DIS_AVE", "GLCM_ENERGY_AVE",
    "GLCM_ENTROPY_AVE", "GLCM_HOM1_AVE", "GLCM_ID_AVE", "GLCM_IDN_AVE",
    "GLCM_IDM_AVE", "GLCM_IDMN_AVE", "GLCM_IV_AVE", "GLCM_JAVE_AVE",
    "GLCM_JE_AVE", "GLCM_INFOMEAS1_AVE", "GLCM_INFOMEAS2_AVE", "GLCM_VARIANCE_AVE",
    "GLCM_JMAX_AVE", "GLCM_JVAR_AVE", "GLCM_SUMAVERAGE_AVE", "GLCM_SUMENTROPY_AVE",
    "GLCM_SUMVARIANCE_AVE",
    # GLRLM Directional (64 features)
    "GLRLM_SRE_0", "GLRLM_SRE_45", "GLRLM_SRE_90", "GLRLM_SRE_135",
    "GLRLM_LRE_0", "GLRLM_LRE_45", "GLRLM_LRE_90", "GLRLM_LRE_135",
    "GLRLM_GLN_0", "GLRLM_GLN_45", "GLRLM_GLN_90", "GLRLM_GLN_135",
    "GLRLM_GLNN_0", "GLRLM_GLNN_45", "GLRLM_GLNN_90", "GLRLM_GLNN_135",
    "GLRLM_RLN_0", "GLRLM_RLN_45", "GLRLM_RLN_90", "GLRLM_RLN_135",
    "GLRLM_RLNN_0", "GLRLM_RLNN_45", "GLRLM_RLNN_90", "GLRLM_RLNN_135",
    "GLRLM_RP_0", "GLRLM_RP_45", "GLRLM_RP_90", "GLRLM_RP_135",
    "GLRLM_GLV_0", "GLRLM_GLV_45", "GLRLM_GLV_90", "GLRLM_GLV_135",
    "GLRLM_RV_0", "GLRLM_RV_45", "GLRLM_RV_90", "GLRLM_RV_135",
    "GLRLM_RE_0", "GLRLM_RE_45", "GLRLM_RE_90", "GLRLM_RE_135",
    "GLRLM_LGLRE_0", "GLRLM_LGLRE_45", "GLRLM_LGLRE_90", "GLRLM_LGLRE_135",
    "GLRLM_HGLRE_0", "GLRLM_HGLRE_45", "GLRLM_HGLRE_90", "GLRLM_HGLRE_135",
    "GLRLM_SRLGLE_0", "GLRLM_SRLGLE_45", "GLRLM_SRLGLE_90", "GLRLM_SRLGLE_135",
    "GLRLM_SRHGLE_0", "GLRLM_SRHGLE_45", "GLRLM_SRHGLE_90", "GLRLM_SRHGLE_135",
    "GLRLM_LRLGLE_0", "GLRLM_LRLGLE_45", "GLRLM_LRLGLE_90", "GLRLM_LRLGLE_135",
    "GLRLM_LRHGLE_0", "GLRLM_LRHGLE_45", "GLRLM_LRHGLE_90", "GLRLM_LRHGLE_135",
    # GLRLM Averaged (16 features)
    "GLRLM_SRE_AVE", "GLRLM_LRE_AVE", "GLRLM_GLN_AVE", "GLRLM_GLNN_AVE",
    "GLRLM_RLN_AVE", "GLRLM_RLNN_AVE", "GLRLM_RP_AVE", "GLRLM_GLV_AVE",
    "GLRLM_RV_AVE", "GLRLM_RE_AVE", "GLRLM_LGLRE_AVE", "GLRLM_HGLRE_AVE",
    "GLRLM_SRLGLE_AVE", "GLRLM_SRHGLE_AVE", "GLRLM_LRLGLE_AVE", "GLRLM_LRHGLE_AVE",
    # Other Texture (33 features)
    "GLSZM_SAE", "GLSZM_LAE", "GLSZM_GLN", "GLSZM_GLNN", "GLSZM_SZN", "GLSZM_SZNN",
    "GLSZM_ZP", "GLSZM_GLV", "GLSZM_ZV", "GLSZM_ZE", "GLSZM_LGLZE", "GLSZM_HGLZE",
    "GLSZM_SALGLE", "GLSZM_SAHGLE", "GLSZM_LALGLE", "GLSZM_LAHGLE",
    "GLDM_SDE", "GLDM_LDE", "GLDM_GLN", "GLDM_DN", "GLDM_DNN", "GLDM_GLV",
    "GLDM_DV", "GLDM_DE", "GLDM_LGLE", "GLDM_HGLE", "GLDM_SDLGLE", "GLDM_SDHGLE",
    "GLDM_LDLGLE", "GLDM_LDHGLE",
    "NGLDM_LDE", "NGLDM_HDE", "NGLDM_LGLCE", "NGLDM_HGLCE", "NGLDM_LDLGLE", "NGLDM_LDHGLE",
    "NGLDM_HDLGLE", "NGLDM_HDHGLE", "NGLDM_GLNU", "NGLDM_GLNUN", "NGLDM_DCNU", "NGLDM_DCNUN",
    "NGLDM_DCP", "NGLDM_GLM", "NGLDM_GLV", "NGLDM_DCM", "NGLDM_DCV", "NGLDM_DCENT",
    "NGLDM_DCENE", "NGTDM_COARSENESS", "NGTDM_CONTRAST", "NGTDM_BUSYNESS",
    "NGTDM_COMPLEXITY", "NGTDM_STRENGTH",
    # Specialized (45 features)
    "FRAC_AT_D_0", "FRAC_AT_D_1", "FRAC_AT_D_2", "FRAC_AT_D_3", "FRAC_AT_D_4",
    "FRAC_AT_D_5", "FRAC_AT_D_6", "FRAC_AT_D_7",
    "GABOR_0", "GABOR_1", "GABOR_2", "GABOR_3",
    "MEAN_FRAC_0", "MEAN_FRAC_1", "MEAN_FRAC_2", "MEAN_FRAC_3",
    "MEAN_FRAC_4", "MEAN_FRAC_5", "MEAN_FRAC_6", "MEAN_FRAC_7",
    "RADIAL_CV_0", "RADIAL_CV_1", "RADIAL_CV_2", "RADIAL_CV_3",
    "RADIAL_CV_4", "RADIAL_CV_5", "RADIAL_CV_6", "RADIAL_CV_7",
    "ZERNIKE2D_Z0", "ZERNIKE2D_Z1", "ZERNIKE2D_Z2", "ZERNIKE2D_Z3",
    "ZERNIKE2D_Z4", "ZERNIKE2D_Z5", "ZERNIKE2D_Z6", "ZERNIKE2D_Z7",
    "ZERNIKE2D_Z8", "ZERNIKE2D_Z9", "ZERNIKE2D_Z10", "ZERNIKE2D_Z11",
    "ZERNIKE2D_Z12", "ZERNIKE2D_Z13", "ZERNIKE2D_Z14", "ZERNIKE2D_Z15",
    "ZERNIKE2D_Z16", "ZERNIKE2D_Z17", "ZERNIKE2D_Z18", "ZERNIKE2D_Z19",
    "ZERNIKE2D_Z20", "ZERNIKE2D_Z21", "ZERNIKE2D_Z22", "ZERNIKE2D_Z23",
    "ZERNIKE2D_Z24", "ZERNIKE2D_Z25", "ZERNIKE2D_Z26", "ZERNIKE2D_Z27",
    "ZERNIKE2D_Z28", "ZERNIKE2D_Z29",
    # Image Moments (177 features - IMOM only)
    "IMOM_RM_00", "IMOM_RM_01", "IMOM_RM_02", "IMOM_RM_03", "IMOM_RM_10",
    "IMOM_RM_11", "IMOM_RM_12", "IMOM_RM_13", "IMOM_RM_20", "IMOM_RM_21",
    "IMOM_RM_22", "IMOM_RM_23", "IMOM_RM_30",
    "IMOM_CM_00", "IMOM_CM_01", "IMOM_CM_02", "IMOM_CM_03", "IMOM_CM_10",
    "IMOM_CM_11", "IMOM_CM_12", "IMOM_CM_13", "IMOM_CM_20", "IMOM_CM_21",
    "IMOM_CM_22", "IMOM_CM_23", "IMOM_CM_30", "IMOM_CM_31", "IMOM_CM_32", "IMOM_CM_33",
    "IMOM_NRM_00", "IMOM_NRM_01", "IMOM_NRM_02", "IMOM_NRM_03", "IMOM_NRM_10",
    "IMOM_NRM_11", "IMOM_NRM_12", "IMOM_NRM_13", "IMOM_NRM_20", "IMOM_NRM_21",
    "IMOM_NRM_22", "IMOM_NRM_23", "IMOM_NRM_30", "IMOM_NRM_31", "IMOM_NRM_32", "IMOM_NRM_33",
    "IMOM_NCM_02", "IMOM_NCM_03", "IMOM_NCM_11", "IMOM_NCM_12", "IMOM_NCM_20",
    "IMOM_NCM_21", "IMOM_NCM_30",
    "IMOM_HU1", "IMOM_HU2", "IMOM_HU3", "IMOM_HU4", "IMOM_HU5", "IMOM_HU6", "IMOM_HU7",
    "IMOM_WRM_00", "IMOM_WRM_01", "IMOM_WRM_02", "IMOM_WRM_03", "IMOM_WRM_10",
    "IMOM_WRM_11", "IMOM_WRM_12", "IMOM_WRM_20", "IMOM_WRM_21", "IMOM_WRM_30",
    "IMOM_WCM_02", "IMOM_WCM_03", "IMOM_WCM_11", "IMOM_WCM_12", "IMOM_WCM_20",
    "IMOM_WCM_21", "IMOM_WCM_30",
    "IMOM_WNCM_02", "IMOM_WNCM_03", "IMOM_WNCM_11", "IMOM_WNCM_12", "IMOM_WNCM_20",
    "IMOM_WNCM_21", "IMOM_WNCM_30",
    "IMOM_WHU1", "IMOM_WHU2", "IMOM_WHU3", "IMOM_WHU4", "IMOM_WHU5", "IMOM_WHU6", "IMOM_WHU7"
]